/* eslint-disable @typescript-eslint/no-explicit-any */
import { NextResponse } from "next/server";
import { authorizeAdminApi } from "@/lib/admin/admin-request";
import { overview, listViews } from "@/lib/analytics/service";
import { appendAdminAuditLog } from "@/lib/admin/audit";
import { getAdminDatabase } from "@/lib/admin/database";
export const runtime = "nodejs";
function dates(url: URL){ const to=Date.parse(url.searchParams.get("to")||"")||Date.now(); const from=Date.parse(url.searchParams.get("from")||"")||to-30*86400000; return {from,to:Math.min(to,Date.now()),ok:from<=to&&to-from<=366*86400000}; }
export async function GET(request: Request){ const a=await authorizeAdminApi(request,"analytics.view",false); if(!a.ok)return NextResponse.json({error:a.error},{status:a.status}); const u=new URL(request.url); const d=dates(u); if(!d.ok)return NextResponse.json({error:"Invalid date range"},{status:400}); const mode=u.searchParams.get("view")||"overview"; if(mode==="visitors"){ const rows=listViews(d.from,d.to,Number(u.searchParams.get("page"))||1,Number(u.searchParams.get("pageSize"))||50); const canIp=a.session.user.role==="OWNER"; return NextResponse.json({rows:rows.map((r:any)=>({...r,ip_address:canIp?r.ip_address:r.ip_address?r.ip_address.replace(/(\d+\.\d+\.)\d+\.\d+$/,"$1x.x"):null}))}); } return NextResponse.json(overview(d.from,d.to,u.searchParams.get("bots")==="1")); }
export async function POST(request: Request){ const a=await authorizeAdminApi(request,"analytics.view",false); if(!a.ok)return NextResponse.json({error:a.error},{status:a.status}); let body:any={}; try{body=await request.json()}catch{} if(body.action!=="export")return NextResponse.json({error:"Invalid action"},{status:400}); const d=dates(new URL(request.url)); const canIp=a.session.user.role==="OWNER"; const rows=listViews(d.from,d.to,1,100000); if(canIp) appendAdminAuditLog(getAdminDatabase(),{actorUserId:a.session.user.id,actorEmail:a.session.user.email,actorRole:a.session.user.role,action:"ANALYTICS_IP_EXPORT",targetType:"analytics",metadata:{count:rows.length}}); const esc=(v:any)=>{const s=String(v??""); return /^[=+\-@]/.test(s)?`'${s}`:s}; const csv=["time,ip,country,path,referrer,browser,os,device,bot",...rows.map((r:any)=>[r.occurred_at,canIp?r.ip_address:"masked",r.country_code,r.pathname,r.referrer,r.browser,r.operating_system,r.device_type,r.is_bot].map(esc).join(","))].join("\n"); return new NextResponse(csv,{headers:{"content-type":"text/csv","content-disposition":"attachment; filename=analytics.csv"}}); }
