import type { OfficialDocument } from "@/types/transparency";

export const OFFICIAL_DOCUMENTS: OfficialDocument[] = [
  {
    slug: "whitepaper",
    title: "Whitepaper",
    version: "2.0.0",
    description: "The complete Green Tree whitepaper covering vision, token identity, market model, treasury, liquidity strategy and environmental commitments.",
    format: "Markdown",
    updatedAt: "2026-07-14",
    category: "Reference",
    path: "/docs/WHITEPAPER.md",
    verifiedOfficial: true,
  },
  {
    slug: "whitepaper-pdf",
    title: "Whitepaper (PDF)",
    version: "2.0.0",
    description: "Formatted PDF edition of the Green Tree whitepaper for offline reading and distribution.",
    format: "PDF",
    updatedAt: "2026-07-14",
    category: "Reference",
    path: "/docs/Green_Tree_Whitepaper_v2.0.0.pdf",
    verifiedOfficial: true,
  },
  {
    slug: "constitution",
    title: "Constitution",
    version: "2.0.0",
    description: "The durable governing principles behind treasury decisions, market conduct, missions and future products.",
    format: "Markdown",
    updatedAt: "2026-07-14",
    category: "Governance",
    path: "/docs/CONSTITUTION.md",
    verifiedOfficial: true,
  },
  {
    slug: "manifest",
    title: "Manifest",
    version: "2.0.0",
    description: "The founding statement of intent behind Green Tree \u2014 why an open market, transparency and nature-aligned action.",
    format: "Markdown",
    updatedAt: "2026-07-14",
    category: "Reference",
    path: "/docs/MANIFEST.md",
    verifiedOfficial: true,
  },
  {
    slug: "token-market-policy",
    title: "Token and Market Policy",
    version: "2.0.0",
    description: "Defines token status, market pricing, website transaction principles and market risk disclosures.",
    format: "Markdown",
    updatedAt: "2026-07-14",
    category: "Policy",
    path: "/docs/TOKEN_MARKET_POLICY.md",
    verifiedOfficial: true,
  },
  {
    slug: "liquidity-policy",
    title: "Liquidity Policy",
    version: "2.0.0",
    description: "Defines the cumulative liquidity thresholds and public reporting requirements for liquidity actions.",
    format: "Markdown",
    updatedAt: "2026-07-14",
    category: "Policy",
    path: "/docs/LIQUIDITY_POLICY.md",
    verifiedOfficial: true,
  },
  {
    slug: "environmental-mission-policy",
    title: "Environmental Mission Policy",
    version: "2.0.0",
    description: "The standard every Green Tree environmental mission must meet, from proposal through final report.",
    format: "Markdown",
    updatedAt: "2026-07-14",
    category: "Policy",
    path: "/docs/ENVIRONMENTAL_MISSION_POLICY.md",
    verifiedOfficial: true,
  },
  {
    slug: "transparency-reporting-policy",
    title: "Transparency and Reporting Policy",
    version: "2.0.0",
    description: "What Green Tree publishes about token authorities, treasury, liquidity, missions and material changes.",
    format: "Markdown",
    updatedAt: "2026-07-14",
    category: "Policy",
    path: "/docs/TRANSPARENCY_AND_REPORTING_POLICY.md",
    verifiedOfficial: true,
  },
  {
    slug: "official-links",
    title: "Official Links",
    version: "2.0.0",
    description: "The canonical list of official Green Tree website, social and token metadata links.",
    format: "Markdown",
    updatedAt: "2026-07-14",
    category: "Reference",
    path: "/docs/OFFICIAL_LINKS.md",
    verifiedOfficial: true,
  },
  {
    slug: "changelog",
    title: "Changelog",
    version: "2.0.0",
    description: "A record of material changes introduced in the Version 2.0.0 open-market launch model.",
    format: "Markdown",
    updatedAt: "2026-07-14",
    category: "Reference",
    path: "/docs/CHANGELOG.md",
    verifiedOfficial: true,
  },
];
