"use client";
import { useEffect, useMemo, useState } from "react";
import { Area, AreaChart, Bar, BarChart, CartesianGrid, ResponsiveContainer, Tooltip, XAxis, YAxis } from "recharts";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";

type AnalyticsData = { summary: Record<string, number>; series: Array<{ day: string; pageViews: number; uniqueVisitors: number; sessions: number }>; pages: Array<{ pathname: string; count: number }> };
const ranges = [{ label: "7 days", days: 7 }, { label: "30 days", days: 30 }, { label: "90 days", days: 90 }];
export default function AnalyticsDashboard() {
  const [days, setDays] = useState(30); const [data, setData] = useState<AnalyticsData | null>(null); const [error, setError] = useState("");
  useEffect(() => { const to = new Date(); const from = new Date(Date.now() - days * 86400000); fetch(`/admin/api/analytics?from=${encodeURIComponent(from.toISOString())}&to=${encodeURIComponent(to.toISOString())}`, { cache: "no-store" }).then((r) => r.ok ? r.json() : Promise.reject()).then(setData).catch(() => setError("Unable to load analytics.")); }, [days]);
  const cards = useMemo(() => [["Page views", data?.summary.pageViews], ["Unique visitors", data?.summary.uniqueVisitors], ["Sessions", data?.summary.sessions], ["Countries", data?.summary.countries], ["Bot requests", data?.summary.bots]], [data]);
  return <section className="space-y-6"><div className="flex flex-wrap items-end justify-between gap-4"><div><p className="text-xs uppercase tracking-[0.25em] text-gt-emerald-bright">First-party reporting</p><h1 className="mt-2 text-3xl font-semibold">Website Analytics</h1><p className="mt-2 text-sm text-gt-muted">Server-side metrics only. Geography is approximate.</p></div><div className="flex rounded-md border border-gt-border p-1">{ranges.map((r) => <button key={r.days} type="button" onClick={() => setDays(r.days)} className={`rounded px-3 py-2 text-xs ${days === r.days ? "bg-gt-emerald text-gt-black" : "text-gt-muted"}`}>{r.label}</button>)}</div></div>{error && <p className="text-gt-danger">{error}</p>}<div className="grid gap-4 sm:grid-cols-2 lg:grid-cols-5">{cards.map(([label, value]) => <Card key={label as string}><CardHeader><CardTitle className="text-sm text-gt-muted">{label}</CardTitle></CardHeader><CardContent><p className="text-2xl font-semibold">{value ?? "—"}</p></CardContent></Card>)}</div><Card><CardHeader><CardTitle>Traffic over time</CardTitle></CardHeader><CardContent><div className="h-72">{data && <ResponsiveContainer width="100%" height="100%"><AreaChart data={data.series}><CartesianGrid stroke="#244044" strokeDasharray="3 3"/><XAxis dataKey="day" tick={{ fill: "#9bb3b3", fontSize: 11 }}/><YAxis tick={{ fill: "#9bb3b3", fontSize: 11 }}/><Tooltip/><Area type="monotone" dataKey="pageViews" stroke="#24c2b8" fill="#24c2b833" name="Page views"/><Area type="monotone" dataKey="uniqueVisitors" stroke="#e2b86b" fill="none" name="Unique visitors"/></AreaChart></ResponsiveContainer>}</div></CardContent></Card><div className="grid gap-6 lg:grid-cols-2"><Card><CardHeader><CardTitle>Top pages</CardTitle></CardHeader><CardContent><div className="h-72">{data && <ResponsiveContainer width="100%" height="100%"><BarChart data={data.pages.slice(0, 10)} layout="vertical" margin={{ left: 20 }}><CartesianGrid stroke="#244044" strokeDasharray="3 3"/><XAxis type="number" tick={{ fill: "#9bb3b3", fontSize: 11 }}/><YAxis dataKey="pathname" type="category" width={120} tick={{ fill: "#9bb3b3", fontSize: 10 }}/><Tooltip/><Bar dataKey="count" fill="#24c2b8" name="Views"/></BarChart></ResponsiveContainer>}</div></CardContent></Card><Card><CardHeader><CardTitle>Recent visitors</CardTitle></CardHeader><CardContent><Visitors days={days}/></CardContent></Card></div></section>;
}
function Visitors({ days }: { days: number }) { const [rows, setRows] = useState<Array<Record<string, string | number>>>([]); useEffect(() => { const from = new Date(Date.now() - days * 86400000).toISOString(); fetch(`/admin/api/analytics?view=visitors&from=${encodeURIComponent(from)}&to=${encodeURIComponent(new Date().toISOString())}`).then((r) => r.json()).then((x) => setRows(x.rows ?? [])).catch(() => undefined); }, [days]); return <div className="max-h-72 overflow-auto text-xs"><div className="grid grid-cols-[1.1fr_1.1fr_1.2fr_0.8fr] gap-2 border-b border-gt-border pb-2 font-medium text-gt-muted"><span>Time</span><span>IP address</span><span>Country</span><span>Device</span></div>{rows.slice(0, 20).map((r, i) => <div key={`${r.occurred_at}-${i}`} className="grid grid-cols-[1.1fr_1.1fr_1.2fr_0.8fr] gap-2 border-b border-gt-border py-2"><span>{new Date(Number(r.occurred_at)).toLocaleString()}</span><span className="truncate" title={String(r.ip_address ?? "")}>{r.ip_address ?? "Unknown IP"}</span><span className="truncate" title={String(r.country_name ?? r.country_code ?? "")}>{r.country_name ?? r.country_code ?? "Unknown country"}</span><span>{r.device_type}</span></div>)}</div>; }
