import "server-only";

import { createHmac, randomUUID, timingSafeEqual } from "node:crypto";
import { getMarketSnapshot } from "@/data/market/get-market-snapshot";
import { getAdminDatabase } from "@/lib/admin/database";
import { getFoundationTransactions } from "@/lib/admin/operations-data";
import { resolveRuntimeSetting } from "@/lib/admin/runtime-settings";
import { PROJECT } from "@/lib/constants/project";
import { getFoundationInventorySnapshot } from "@/lib/purchase/foundation-inventory-server";
import { SupportService } from "@/lib/support/service";
import type { SupportTopic } from "@/lib/support/repository";
import { PartnershipService, PUBLIC_PARTNERSHIP_CATEGORIES } from "@/lib/partnerships/service";
import { getOnChainGtreeBalance, getVerifiedTelegramWallet, getWalletPurchaseHistory, getWalletPurchaseSummary } from "@/lib/telegram/wallet-data";
import { enqueueNotification } from "@/lib/telegram/notification-outbox";

type TelegramUser = { id: number; username?: string; language_code?: string };
type TelegramMessage = { message_id: number; chat: { id: number; type?: string }; from?: TelegramUser; text?: string };
export type TelegramUpdate = { update_id: number; message?: TelegramMessage; callback_query?: { id: string; from: TelegramUser; message?: TelegramMessage; data?: string } };
export type ConversationState = "IDLE" | "SUPPORT_CATEGORY" | "SUPPORT_MESSAGE" | "SUPPORT_REFERENCE" | "PARTNERSHIP_CATEGORY" | "PARTNERSHIP_NAME" | "PARTNERSHIP_CONTACT" | "PARTNERSHIP_PROPOSAL";

type TelegramUrlOptions = { baseUrl?: string; path?: string };
function readBoolean(name: string, fallback: boolean) { const value = process.env[name]?.trim().toLowerCase(); return value ? value === "true" : fallback; }
export function buildTelegramWebAppUrl(options: TelegramUrlOptions = {}) {
  const rawBase = (options.baseUrl ?? process.env.TELEGRAM_WEB_APP_URL ?? PROJECT.website).trim();
  const path = options.path ?? process.env.TELEGRAM_PURCHASE_PATH ?? "/market?source=telegram_mini_app&action=buy";
  try { const base = new URL(rawBase); if (base.protocol !== "https:" || base.hostname !== "gtree.land") return null; return new URL(path, base).toString(); } catch { return null; }
}
export function telegramConfig() {
  const token = process.env.TELEGRAM_BOT_TOKEN?.trim() ?? "";
  const secret = process.env.TELEGRAM_WEBHOOK_SECRET?.trim() ?? "";
  const miniAppUrl = process.env.TELEGRAM_MINI_APP_URL?.trim() || `${PROJECT.website}/telegram`;
  const purchaseUrl = buildTelegramWebAppUrl();
  const connectUrl = buildTelegramWebAppUrl({ baseUrl: miniAppUrl, path: "/telegram?flow=connect" });
  const purchaseEnabled = readBoolean("TELEGRAM_PURCHASE_ENABLED", readBoolean("TELEGRAM_SALES_ENABLED", false));
  return { enabled: readBoolean("TELEGRAM_BOT_ENABLED", false) && Boolean(token && secret), token, secret, salesEnabled: purchaseEnabled, purchaseEnabled, supportEnabled: readBoolean("TELEGRAM_SUPPORT_ENABLED", true), miniAppUrl, purchaseUrl, connectUrl, username: process.env.TELEGRAM_BOT_USERNAME?.trim() ?? "", operationsChannelId: process.env.TELEGRAM_OPERATIONS_CHANNEL_ID?.trim() ?? "", adminGroupId: process.env.TELEGRAM_ADMIN_GROUP_ID?.trim() ?? "" };
}
function numericIds(name: string) { return new Set((process.env[name] ?? "").split(",").map((v) => v.trim()).filter((v) => /^\d+$/.test(v))); }
export function isAdminChat(chatId: string) { return Boolean(telegramConfig().adminGroupId) && chatId === telegramConfig().adminGroupId; }
export function isOperationsChat(chatId: string) { return Boolean(telegramConfig().operationsChannelId) && chatId === telegramConfig().operationsChannelId; }
export function isAuthorizedAdmin(userId: number, ownerOnly = false) { const ids = ownerOnly ? numericIds("TELEGRAM_OWNER_USER_IDS") : new Set([...numericIds("TELEGRAM_OWNER_USER_IDS"), ...numericIds("TELEGRAM_ADMIN_USER_IDS")]); return ids.has(String(userId)); }
export function conversationKey(userHash: string, chatId: string) { return `${userHash}:${chatId}`; }
const GLOBAL_TEXT_ACTIONS = new Set(["/start", "/buy", "/connect", "/admin", "My GTREE", "Purchase History", "🔗 Connect Wallet", "📈 Live Price", "🧾 Recent Activity", "🛒 Buy GTREE", "🛟 Support", "🤝 Partnership", "🌐 Open Green Tree", "🟢 Service Status", "❔ Help", "Back", "Cancel", "Main Menu"]);
export function isGlobalTelegramAction(value: string) { return GLOBAL_TEXT_ACTIONS.has(value.trim()); }
export function parsePublicCallback(value: string) { const match = /^public:(buy|connect_wallet|my_gtree|purchase_history|live_price|recent_activity|support|partnership|service_status|main_menu)$/.exec(value.trim()); return match?.[1] ?? null; }
export function validWebhookSecret(value: string | null) { const expected = telegramConfig().secret; if (!expected || !value) return false; return value.length === expected.length && timingSafeEqual(Buffer.from(value), Buffer.from(expected)); }
export function hashTelegram(value: string) { const secret = process.env.ADMIN_IP_HMAC_SECRET ?? ""; if (secret.length < 32) throw new Error("Telegram identity hashing is unavailable."); return createHmac("sha256", secret).update(`telegram\0${value}`).digest("hex"); }
export function telegramEnabled() { return telegramConfig().enabled; }
export async function telegramApi(method: string, body: Record<string, unknown>) {
  const config = telegramConfig(); if (!config.enabled) throw new Error("Telegram bot is not configured.");
  const response = await fetch(`https://api.telegram.org/bot${config.token}/${method}`, { method: "POST", headers: { "content-type": "application/json" }, body: JSON.stringify(body), signal: AbortSignal.timeout(8_000) });
  const json = await response.json().catch(() => null) as { ok?: boolean; result?: unknown; description?: string } | null;
  try { getAdminDatabase().db.prepare("INSERT INTO telegram_runtime_state (key, value, updated_at) VALUES ('last_bot_request', ?, ?) ON CONFLICT(key) DO UPDATE SET value=excluded.value, updated_at=excluded.updated_at").run(response.ok && json?.ok ? "ok" : "failed", Date.now()); } catch { /* telemetry must not break the bot */ }
  if (!response.ok || !json?.ok) throw new Error(`Telegram request failed: ${json?.description ?? response.status}`);
  return json.result;
}

export async function processTelegramUpdate(update: TelegramUpdate) {
  const db = getAdminDatabase();
  try { db.db.prepare("INSERT INTO telegram_updates (update_id, received_at) VALUES (?, ?)").run(update.update_id, Date.now()); } catch { return { duplicate: true }; }
  const message = update.message ?? update.callback_query?.message; const user = update.message?.from ?? update.callback_query?.from;
  if (!message || !user) return { ignored: true };
  const chatId = String(message.chat.id); const userHash = hashTelegram(String(user.id));
  if (isOperationsChat(chatId)) return { ignored: true, reason: "operations_channel_reports_only" };
  const text = (update.message?.text ?? update.callback_query?.data ?? "").trim();
  if (update.callback_query) {
    try { await telegramApi("answerCallbackQuery", { callback_query_id: update.callback_query.id }); } catch { /* best effort */ }
    const publicAction = parsePublicCallback(text);
    if (publicAction) { clearConversation(userHash, chatId); return dispatchPublicAction(publicAction, chatId, user.id, userHash, user); }
    const historyPage = parseHistoryPageCallback(text); if (historyPage !== null) return history(chatId, user.id, historyPage);
    if (text === "HISTORY_BACK") return myGtree(chatId, user.id);
    if (text === "ACTIVITY_BACK") return activity(chatId, 1);
    if (/^ACTIVITY_PAGE:[1-9]\d{0,4}$/.test(text)) return activity(chatId, Number(text.split(":")[1]));
    if (text === "support:cancel" || text === "SUPPORT_CANCEL" || text === "/cancel") { clearConversation(userHash, chatId); return send(chatId, "Flow cancelled.", mainMenuMarkup()); }
    if (/^support:category:(purchase|website|general)$/.test(text) || /^SUPPORT_(PURCHASE|WEBSITE|GENERAL)$/.test(text)) { const supportState = getConversation(userHash, chatId); return supportState?.state === "SUPPORT_CATEGORY" ? processSupport(chatId, user, userHash, text, supportState) : send(chatId, "This support step has expired.", mainMenuMarkup()); }
    if (text.startsWith("partnership:")) return processPartnershipCallback(chatId, user, userHash, text);
    if (text.startsWith("admin:")) return processAdminCallback(chatId, user, text);
  }
  if (isGlobalTelegramAction(text)) {
    clearConversation(userHash, chatId);
    if (text === "/admin") return adminPanel(chatId, user);
    if (text === "/start" || text === "❔ Help" || text === "Main Menu") return send(chatId, "Welcome to Green Tree. Choose an action below.", mainMenuMarkup());
    if (text === "/buy" || text === "🛒 Buy GTREE") return buy(chatId);
    if (text === "/connect" || text === "🔗 Connect Wallet") return connectWallet(chatId);
    if (text === "My GTREE") return myGtree(chatId, user.id); if (text === "Purchase History") return history(chatId, user.id, 1);
    if (text === "📈 Live Price") return price(chatId); if (text === "🧾 Recent Activity") return activity(chatId, 1);
    if (text === "🛟 Support") return startSupport(chatId, userHash, user); if (text === "🤝 Partnership") return startPartnership(chatId, userHash, user);
    if (text === "🌐 Open Green Tree") return send(chatId, "Open Green Tree:", { inline_keyboard: [[{ text: "Open website", web_app: { url: telegramConfig().miniAppUrl } }]] });
    if (text === "🟢 Service Status") return serviceStatus(chatId);
    return send(chatId, "Flow cancelled.", mainMenuMarkup());
  }
  const conversation = getConversation(userHash, chatId);
  if (conversation?.state.startsWith("SUPPORT")) return processSupport(chatId, user, userHash, text, conversation);
  if (conversation?.state.startsWith("PARTNERSHIP")) return processPartnership(chatId, user, userHash, text, conversation);
  return send(chatId, "Please choose an action from the menu below.", mainMenuMarkup());
}
async function dispatchPublicAction(action: string, chatId: string, userId: number, userHash: string, user: TelegramUser) {
  if (action === "buy") return buy(chatId); if (action === "connect_wallet") return connectWallet(chatId); if (action === "my_gtree") return myGtree(chatId, userId); if (action === "purchase_history") return history(chatId, userId, 1); if (action === "live_price") return price(chatId); if (action === "recent_activity") return activity(chatId, 1); if (action === "support") return startSupport(chatId, userHash, user); if (action === "partnership") return startPartnership(chatId, userHash, user); if (action === "service_status") return serviceStatus(chatId); return send(chatId, "Welcome to Green Tree. Choose an action below.", mainMenuMarkup());
}

async function price(chatId: string) { const result = await getMarketSnapshot(); if (result.status !== "ready" || !result.data) return send(chatId, "Market data is currently unavailable.", mainMenuMarkup()); const data = result.data; return send(chatId, `GTREE live market\nGTREE/USD: $${data.gtreeUsd}\nGTREE/SOL: ${data.priceSol} SOL\nSOL/USD: $${data.solUsd}\nStatus: ${result.stale ? "STALE" : "LIVE"}\nUpdated: ${data.fetchedAt}`, { inline_keyboard: [[{ text: "View Market", url: "https://gtree.land/market" }], [{ text: "Main Menu", callback_data: "public:main_menu" }]] }); }
async function activity(chatId: string, page = 1) { const result = getFoundationTransactions({ view: "CONFIRMED", page, pageSize: 5 }); const rows = result.available ? result.items : []; const totalPages = result.available ? Math.max(1, Math.ceil(result.total / result.pageSize)) : 1; const content = rows.length ? rows.map((row) => `${short(row.buyer)} · ${format(row.inputLamports)} SOL · ${format(row.outputTokenUnits)} GTREE\n${new Date(row.confirmedAt ?? row.createdAt).toLocaleString()}${row.signature ? `\nhttps://solscan.io/tx/${row.signature}` : ""}`).join("\n\n") : "No confirmed Foundation purchases have been recorded yet."; const buttons: Array<Array<{ text: string; callback_data: string }>> = []; if (page > 1) buttons.push([{ text: "Previous", callback_data: `ACTIVITY_PAGE:${page - 1}` }]); if (page < totalPages) buttons.push([{ text: "Next", callback_data: `ACTIVITY_PAGE:${page + 1}` }]); buttons.push([{ text: "Main Menu", callback_data: "public:main_menu" }]); return send(chatId, `Recent Foundation Activity · Page ${page}/${totalPages}\n\n${content}`, { inline_keyboard: buttons }); }
async function buy(chatId: string) { const config = telegramConfig(); if (!config.purchaseEnabled || resolveRuntimeSetting("purchaseMode") !== "FOUNDATION_DIRECT" || !config.purchaseUrl) return send(chatId, "Sales through Telegram are temporarily unavailable. You can still view the market or contact Support.", mainMenuMarkup()); const inventory = await getFoundationInventorySnapshot().catch(() => null); return send(chatId, `Foundation Direct availability: ${inventory?.spendableGtree ?? "Unavailable"} GTREE`, { inline_keyboard: [[{ text: "🛒 Open Buy GTREE", web_app: { url: config.purchaseUrl } }], [{ text: "Main Menu", callback_data: "public:main_menu" }]] }); }
async function connectWallet(chatId: string) { const config = telegramConfig(); if (!config.connectUrl) return send(chatId, "Wallet connection is temporarily unavailable. Open Green Tree in a secure browser and try again.", mainMenuMarkup()); return send(chatId, "Connect a Solana wallet to Green Tree. You will sign an ownership message only; never send a seed phrase or private key.", { inline_keyboard: [[{ text: "🔗 Connect Wallet", web_app: { url: config.connectUrl } }], [{ text: "Main Menu", callback_data: "public:main_menu" }]] }); }
async function myGtree(chatId: string, telegramUserId: number) { const wallet = getVerifiedTelegramWallet(String(telegramUserId)); if (!wallet) return send(chatId, "Connect and verify your wallet first.", { inline_keyboard: [[{ text: "🔗 Connect Wallet", callback_data: "public:connect_wallet" }], [{ text: "Main Menu", callback_data: "public:main_menu" }]] }); const summary = getWalletPurchaseSummary(wallet); const balance = await getOnChainGtreeBalance(wallet); const balanceText = balance.lookupStatus === "rpc_error" ? "Temporarily unavailable" : `${balance.gtreeBalance} GTREE`; const recent = summary.latestConfirmedPurchases.slice(0, 3).map((row) => `${format(row.gtreeTokenUnits)} GTREE · ${new Date(row.confirmedAt ?? row.createdAt).toLocaleDateString()}${row.transactionSignature ? `\nhttps://solscan.io/tx/${row.transactionSignature}` : ""}`).join("\n\n") || "No confirmed purchases yet."; return send(chatId, `Verified Wallet\n${short(wallet)}\n\nOn-chain GTREE Balance\n${balanceText}\n\nWebsite-confirmed GTREE Purchased\n${format(summary.confirmedGtreeTokenUnits)} GTREE\n\nConfirmed SOL Spent\n${format(summary.confirmedSolLamports)} SOL\n\nConfirmed Purchases: ${summary.confirmedPurchaseCount}\nPending Purchases: ${summary.pendingPurchaseCount}\n\nRecent purchases\n${recent}`, { inline_keyboard: [[{ text: "Purchase History", callback_data: "public:purchase_history" }], [{ text: "Main Menu", callback_data: "public:main_menu" }]] }); }
async function history(chatId: string, telegramUserId: number, page: number) { const wallet = getVerifiedTelegramWallet(String(telegramUserId)); if (!wallet) return send(chatId, "Connect and verify your wallet first.", { inline_keyboard: [[{ text: "🔗 Connect Wallet", callback_data: "public:connect_wallet" }], [{ text: "Main Menu", callback_data: "public:main_menu" }]] }); const result = getWalletPurchaseHistory(wallet, page, 5); if (!result.items.length) return send(chatId, "No purchases found for your verified wallet.", { inline_keyboard: [[{ text: "Back to My GTREE", callback_data: "HISTORY_BACK" }]] }); const content = result.items.map((row) => `${row.status} · ${format(row.gtreeTokenUnits)} GTREE · ${format(row.solLamports)} SOL\n${new Date(row.confirmedAt ?? row.updatedAt ?? row.createdAt).toLocaleString()}${row.transactionSignature ? `\nhttps://solscan.io/tx/${row.transactionSignature}` : ""}`).join("\n\n"); const buttons: Array<Array<{ text: string; callback_data: string }>> = []; if (result.page > 1) buttons.push([{ text: "Previous", callback_data: `HISTORY_PAGE:${result.page - 1}` }]); if (result.page < result.totalPages) buttons.push([{ text: "Next", callback_data: `HISTORY_PAGE:${result.page + 1}` }]); buttons.push([{ text: "Back to My GTREE", callback_data: "HISTORY_BACK" }]); return send(chatId, `Purchase History · Page ${result.page}/${result.totalPages}\n\n${content}`, { inline_keyboard: buttons }); }

async function startSupport(chatId: string, userHash: string, user: TelegramUser) { if (!telegramConfig().supportEnabled) return send(chatId, "Telegram Support is temporarily unavailable.", mainMenuMarkup()); setConversation(userHash, chatId, user.username, "SUPPORT_CATEGORY", {}); return send(chatId, "Choose a support category:", categories()); }
async function processSupport(chatId: string, user: TelegramUser, userHash: string, text: string, state: { state: ConversationState; payload: Record<string, string> }) { if (state.state === "SUPPORT_CATEGORY") { const topic = (text.match(/(?:support:category:|SUPPORT_)(purchase|website|general)/i)?.[1] ?? "").toUpperCase() as SupportTopic; if (!["PURCHASE", "WEBSITE", "GENERAL"].includes(topic)) return send(chatId, "Choose a category using the buttons:", categories()); setConversation(userHash, chatId, user.username, "SUPPORT_MESSAGE", { topic }); return send(chatId, "Please describe the issue concisely. Never send a seed phrase or private key.", flowControls()); } if (state.state === "SUPPORT_MESSAGE") { if (text.length < 10) return send(chatId, "Please provide at least 10 characters.", flowControls()); setConversation(userHash, chatId, user.username, "SUPPORT_REFERENCE", { ...state.payload, message: text }); return send(chatId, "Optional: send an order ID, transaction signature, or wallet address. Send - to skip.", flowControls()); } const result = new SupportService().submitTelegram({ userHash, chatId, chatHash: hashTelegram(chatId), username: user.username, topic: state.payload.topic as SupportTopic, message: state.payload.message, reference: text === "-" ? undefined : text }); try { enqueueNotification({ eventType: "support_submitted", entityType: "support_request", entityId: result.requestNumber, idempotencyKey: `support-submitted:${result.requestNumber}`, payload: { requestNumber: result.requestNumber, topic: state.payload.topic, duplicate: result.duplicate, timestamp: Date.now() } }); } catch { /* reporting is best effort */ } clearConversation(userHash, chatId); return send(chatId, `${result.duplicate ? "Your matching ticket already exists" : "Support request received"}.\nTracking code: ${result.requestNumber}`, mainMenuMarkup()); }
async function startPartnership(chatId: string, userHash: string, user: TelegramUser) { setConversation(userHash, chatId, user.username, "PARTNERSHIP_CATEGORY", {}); const buttons: Array<Array<{ text: string; callback_data: string }>> = PUBLIC_PARTNERSHIP_CATEGORIES.slice(0, 6).map((category) => [{ text: category, callback_data: `partnership:category:${category}` }]); buttons.push([{ text: "Cancel", callback_data: "support:cancel" }]); return send(chatId, "Choose a partnership category:", { inline_keyboard: buttons }); }
async function processPartnershipCallback(chatId: string, user: TelegramUser, userHash: string, text: string) { const category = /^partnership:category:([A-Z]+)$/.exec(text)?.[1]; const state = getConversation(userHash, chatId); if (!category || !state || state.state !== "PARTNERSHIP_CATEGORY" || !PUBLIC_PARTNERSHIP_CATEGORIES.includes(category as typeof PUBLIC_PARTNERSHIP_CATEGORIES[number])) return send(chatId, "This partnership step has expired.", mainMenuMarkup()); setConversation(userHash, chatId, user.username, "PARTNERSHIP_NAME", { category }); return send(chatId, "Send your name or project name.", flowControls()); }
async function processPartnership(chatId: string, user: TelegramUser, userHash: string, text: string, state: { state: ConversationState; payload: Record<string, string> }) { if (text.length < 2) return send(chatId, "Please enter a little more detail.", flowControls()); if (state.state === "PARTNERSHIP_NAME") { setConversation(userHash, chatId, user.username, "PARTNERSHIP_CONTACT", { ...state.payload, nameOrProject: text }); return send(chatId, "Send a contact handle or email.", flowControls()); } if (state.state === "PARTNERSHIP_CONTACT") { setConversation(userHash, chatId, user.username, "PARTNERSHIP_PROPOSAL", { ...state.payload, contact: text, contactType: text.includes("@") ? "EMAIL" : "TELEGRAM" }); return send(chatId, "Describe the proposal in at least 10 characters.", flowControls()); } const result = new PartnershipService().submit({ ...state.payload, proposal: text, startedAt: Date.now() - 2_000 }, "telegram"); try { enqueueNotification({ eventType: "partnership_submitted", entityType: "partnership", entityId: result.requestNumber, idempotencyKey: `partnership-submitted:${result.requestNumber}`, payload: { requestNumber: result.requestNumber, timestamp: Date.now() } }); } catch { /* best effort */ } clearConversation(userHash, chatId); return send(chatId, `Partnership request received.\nReference: ${result.requestNumber}`, mainMenuMarkup()); }

async function serviceStatus(chatId: string) { const config = telegramConfig(); return send(chatId, `Service Status\nWebsite: LIVE\nPurchase API: ${config.purchaseEnabled && resolveRuntimeSetting("purchaseMode") === "FOUNDATION_DIRECT" ? "AVAILABLE" : "PAUSED"}\nTelegram webhook: ${telegramEnabled() ? "LIVE" : "UNAVAILABLE"}\nWorker: ${process.env.TELEGRAM_NOTIFICATION_WORKER_ENABLED === "false" ? "PAUSED" : "CONFIGURED"}\nSolana RPC: CONFIGURED`, mainMenuMarkup()); }
async function processAdminCallback(chatId: string, user: TelegramUser, text: string) { if (!isAdminChat(chatId) || !isAuthorizedAdmin(user.id)) return send(chatId, "Access denied."); if (text === "admin:dashboard" || text === "admin:refresh") return adminPanel(chatId, user); if (text === "admin:distribution_balance") { const inventory = await getFoundationInventorySnapshot().catch(() => null); return send(chatId, `Distribution Balance\nSource balance: ${inventory?.spendableGtree ?? "Unavailable"} GTREE`); } if (text === "admin:analytics") return send(chatId, "Analytics summary is available through the existing admin dashboard."); if (text === "admin:distribution_create") { if (!isAuthorizedAdmin(user.id, true)) return send(chatId, "OWNER authorization required."); return send(chatId, "Manual GTREE Distribution is in dry-run verification mode. Use the admin dashboard for the full preview."); } if (["admin:quotes", "admin:purchases", "admin:transactions", "admin:transactions_failed", "admin:support", "admin:partnerships", "admin:distribution_pending", "admin:distribution_recent", "admin:notifications_failed"].includes(text)) return send(chatId, "This operational view is available in the Green Tree admin dashboard."); return send(chatId, "This admin action is not available."); }
async function adminPanel(chatId: string, user: TelegramUser) { if (!isAdminChat(chatId) || !isAuthorizedAdmin(user.id)) return send(chatId, "Access denied."); const buttons = [[{ text: "Operations Summary", callback_data: "admin:dashboard" }, { text: "Pending Quotes", callback_data: "admin:quotes" }], [{ text: "Recent Purchases", callback_data: "admin:purchases" }, { text: "Recent Transactions", callback_data: "admin:transactions" }], [{ text: "Failed Transactions", callback_data: "admin:transactions_failed" }, { text: "Support Queue", callback_data: "admin:support" }], [{ text: "Partnership Queue", callback_data: "admin:partnerships" }, { text: "Analytics Summary", callback_data: "admin:analytics" }], [{ text: "Distribution Balance", callback_data: "admin:distribution_balance" }, { text: "Manual GTREE Distribution", callback_data: "admin:distribution_create" }], [{ text: "Pending Distributions", callback_data: "admin:distribution_pending" }, { text: "Recent Distributions", callback_data: "admin:distribution_recent" }], [{ text: "Failed Notifications", callback_data: "admin:notifications_failed" }, { text: "Refresh Panel", callback_data: "admin:refresh" }]]; return send(chatId, "Green Tree Admin Operations", { inline_keyboard: buttons }); }
function getConversation(userHash: string, chatId: string) { const row = getAdminDatabase().db.prepare("SELECT state, payload_json FROM telegram_conversations WHERE user_hash = ? AND chat_id = ? AND expires_at > ?").get(userHash, chatId, Date.now()) as { state: ConversationState; payload_json: string } | undefined; if (!row) return null; try { return { state: row.state, payload: JSON.parse(row.payload_json) as Record<string, string> }; } catch { return null; } }
function setConversation(userHash: string, chatId: string, username: string | undefined, state: ConversationState, payload: Record<string, string>) { const now = Date.now(); getAdminDatabase().db.prepare("INSERT INTO telegram_conversations (user_hash, chat_id, username, state, payload_json, expires_at, updated_at) VALUES (?, ?, ?, ?, ?, ?, ?) ON CONFLICT(user_hash, chat_id) DO UPDATE SET username=excluded.username, state=excluded.state, payload_json=excluded.payload_json, expires_at=excluded.expires_at, updated_at=excluded.updated_at").run(userHash, chatId, username ?? null, state, JSON.stringify(payload), now + 20 * 60_000, now); }
function clearConversation(userHash: string, chatId: string) { getAdminDatabase().db.prepare("DELETE FROM telegram_conversations WHERE user_hash = ? AND chat_id = ?").run(userHash, chatId); }
function send(chatId: string, text: string, reply_markup: Record<string, unknown> = telegramMenu()) { return telegramApi("sendMessage", { chat_id: chatId, text, reply_markup, disable_web_page_preview: true }); }
export function telegramMenu() { const config = telegramConfig(); return { keyboard: [[{ text: "🛒 Buy GTREE", web_app: config.purchaseUrl ? { url: config.purchaseUrl } : undefined }, { text: "📈 Live Price" }], [{ text: "🔗 Connect Wallet", web_app: config.connectUrl ? { url: config.connectUrl } : undefined }, { text: "My GTREE" }], [{ text: "Purchase History" }, { text: "🧾 Recent Activity" }], [{ text: "🛟 Support" }, { text: "🤝 Partnership" }], [{ text: "🌐 Open Green Tree", web_app: { url: config.miniAppUrl } }, { text: "🟢 Service Status" }], [{ text: "❔ Help" }]], resize_keyboard: true, is_persistent: true }; }
function mainMenuMarkup() { return { inline_keyboard: [[{ text: "🛒 Buy GTREE", callback_data: "public:buy" }, { text: "🔗 Connect Wallet", callback_data: "public:connect_wallet" }], [{ text: "My GTREE", callback_data: "public:my_gtree" }, { text: "Purchase History", callback_data: "public:purchase_history" }], [{ text: "📈 Live Price", callback_data: "public:live_price" }, { text: "🧾 Recent Activity", callback_data: "public:recent_activity" }], [{ text: "🛟 Support", callback_data: "public:support" }, { text: "🤝 Partnership", callback_data: "public:partnership" }], [{ text: "🟢 Service Status", callback_data: "public:service_status" }]] }; }
function flowControls() { return { inline_keyboard: [[{ text: "Cancel", callback_data: "support:cancel" }, { text: "Main Menu", callback_data: "public:main_menu" }]] }; }
function categories() { return { inline_keyboard: [[{ text: "🛒 Purchase issue", callback_data: "support:category:purchase" }, { text: "🛠 Technical issue", callback_data: "support:category:website" }], [{ text: "🌳 Token information", callback_data: "support:category:general" }], [{ text: "Cancel", callback_data: "support:cancel" }]] }; }
function short(value: string) { return `${value.slice(0, 5)}…${value.slice(-4)}`; }
function format(raw: string, decimals = 9) { const value = BigInt(raw); const scale = 10n ** BigInt(decimals); const whole = value / scale; const fraction = (value % scale).toString().padStart(decimals, "0").slice(0, 4).replace(/0+$/, ""); return fraction ? `${whole}.${fraction}` : whole.toString(); }
export function parseHistoryPageCallback(value: string): number | null { const match = /^HISTORY_PAGE:([1-9]\d{0,5})$/.exec(value.trim()); if (!match) return null; const page = Number(match[1]); return page >= 1 && page <= 100_000 ? page : null; }
export function validateInitData(initData: string) { const token = telegramConfig().token; if (!token || !initData) return null; const params = new URLSearchParams(initData); const hash = params.get("hash"); params.delete("hash"); const dataCheck = [...params.entries()].sort(([a], [b]) => a.localeCompare(b)).map(([key, value]) => `${key}=${value}`).join("\n"); const secret = createHmac("sha256", "WebAppData").update(token).digest(); const expected = createHmac("sha256", secret).update(dataCheck).digest("hex"); if (!hash || hash.length !== expected.length || !timingSafeEqual(Buffer.from(hash), Buffer.from(expected))) return null; const authDate = Number(params.get("auth_date")); if (!Number.isFinite(authDate) || Date.now() - authDate * 1_000 > 300_000) return null; try { const user = JSON.parse(params.get("user") ?? "") as { id?: number; username?: string; language_code?: string }; if (!Number.isSafeInteger(user.id) || user.id! < 0) return null; return { telegramUserId: String(user.id), userHash: hashTelegram(String(user.id)), username: user.username, language: user.language_code ?? null, sessionId: randomUUID(), expiresAt: Date.now() + 300_000 }; } catch { return null; } }
