import Link from "next/link";
import { notFound, redirect } from "next/navigation";
import { SupportActions } from "@/components/admin/support-actions";
import { hasAdminPermission } from "@/lib/admin/permissions";
import { getCurrentAdminSession } from "@/lib/admin/request";
import { getSupportRepository } from "@/lib/support/repository";

export const dynamic = "force-dynamic";
export default async function SupportDetailPage({ params }: { params: Promise<{ id: string }> }) {
  const session = await getCurrentAdminSession(); if (!session) redirect("/admin/login"); if (!hasAdminPermission(session.user.role, "support.read")) redirect("/admin");
  const repository = getSupportRepository(); const request = repository.findById((await params).id); if (!request) notFound();
  const timeline = repository.timeline(request.id); const notes = repository.notes(request.id); const canManage = hasAdminPermission(session.user.role, "support.write");
  return <section><Link href="/admin/support" className="text-sm text-gt-emerald-bright">← Support</Link><div className="mt-5 flex flex-wrap items-start justify-between gap-4"><div><p className="font-mono text-xs uppercase tracking-[0.18em] text-gt-info">{request.topic}</p><h1 className="mt-2 text-3xl font-semibold">{request.requestNumber}</h1><p className="mt-2 text-sm text-gt-muted">Submitted {new Date(request.submittedAt).toLocaleString()} · {request.status}</p></div><span className="rounded-full border border-gt-border px-3 py-1 text-xs">{request.status}</span></div><div className="mt-8 grid gap-7 xl:grid-cols-[minmax(0,1fr)_360px]"><div className="space-y-7"><article className="rounded-lg border border-gt-border bg-gt-surface/45 p-5"><h2 className="text-lg font-semibold">Support request</h2><dl className="mt-5 grid gap-5 sm:grid-cols-2"><Item label="Requester" value={request.requesterName}/><Item label="Reply email" value={request.replyEmail} href={`mailto:${request.replyEmail}`}/><Item label="Topic" value={request.topic}/><Item label="Tracking code" value={request.requestNumber}/></dl><div className="mt-6 border-t border-gt-border pt-5"><h3 className="text-xs uppercase tracking-wide text-gt-muted">Message</h3><p className="mt-2 whitespace-pre-wrap text-sm leading-6">{request.message}</p></div></article><section><h2 className="text-lg font-semibold">Internal notes</h2><div className="mt-3 space-y-3">{notes.map((note) => <div key={note.id} className="rounded-lg border border-gt-border bg-gt-surface/35 p-4"><p className="whitespace-pre-wrap text-sm leading-6">{note.body}</p><p className="mt-3 text-xs text-gt-muted">{note.authorEmail ?? "Former administrator"} · {new Date(note.createdAt).toLocaleString()}</p></div>)}{!notes.length && <p className="rounded-lg border border-dashed border-gt-border p-5 text-sm text-gt-muted">No internal notes.</p>}</div></section></div><aside className="space-y-7">{canManage && <section className="rounded-lg border border-gt-border bg-gt-surface/45 p-5"><h2 className="mb-5 text-lg font-semibold">Manage request</h2><SupportActions id={request.id} status={request.status} csrfToken={session.csrfToken}/></section>}<section><h2 className="text-lg font-semibold">Timeline</h2><ol className="mt-4 border-l border-gt-border pl-5">{timeline.map((event) => <li key={event.id} className="relative pb-5 text-sm"><span className="absolute -left-[23px] top-1 size-2 rounded-full bg-gt-info"/><p className="font-medium">{event.eventType.replaceAll("_", " ")}</p>{(event.fromStatus || event.toStatus) && <p className="text-gt-muted">{event.fromStatus ?? "—"} → {event.toStatus ?? "—"}</p>}<p className="mt-1 text-xs text-gt-muted">{event.actorEmail ?? "Public submission"} · {new Date(event.createdAt).toLocaleString()}</p></li>)}</ol></section></aside></div></section>;
}
function Item({ label, value, href }: { label: string; value: string; href?: string }) { return <div><dt className="text-xs uppercase tracking-wide text-gt-muted">{label}</dt><dd className="mt-1 break-words text-sm">{href ? <a className="text-gt-emerald-bright hover:underline" href={href}>{value}</a> : value}</dd></div>; }
