"use client";
import { useEffect, useMemo, useState } from "react";
import { Button } from "@/components/ui/button";
import { decimalToAtomic, atomicToDecimal } from "@/lib/market/amounts";

type Snapshot = { gtreeUsd: number; priceSol: number; solUsd: number; sourceStatus: string; fetchedAt: string };
type Inventory = { spendableGtree: string; status: string };
export function TelegramMiniApp() {
  const [snapshot, setSnapshot] = useState<Snapshot | null>(null); const [inventory, setInventory] = useState<Inventory | null>(null); const [sol, setSol] = useState(""); const [status, setStatus] = useState("LIVE"); const [notice, setNotice] = useState("");
  useEffect(() => { void Promise.all([fetch("/api/market/snapshot").then((r) => r.json()), fetch("/api/foundation/inventory").then((r) => r.json())]).then(([market, foundation]) => { setSnapshot(market.data ?? null); setInventory(foundation.data ?? foundation); }); const initData = (window as Window & { Telegram?: { WebApp?: { initData?: string } } }).Telegram?.WebApp?.initData; if (initData) void fetch("/api/telegram/session", { method: "POST", headers: { "content-type": "application/json" }, body: JSON.stringify({ initData }) }); }, []);
  const estimate = useMemo(() => { if (!snapshot || !sol) return null; try { const lamports = BigInt(decimalToAtomic(sol, 9).raw); return (lamports * BigInt(Math.floor((1 / snapshot.priceSol) * 1e9))) / 1_000_000_000n; } catch { return null; } }, [sol, snapshot]);
  async function review() { setNotice(""); try { const wallet = ""; if (!wallet) throw new Error("Open secure checkout in your browser to connect a Solana wallet and review the transaction."); } catch (error) { setNotice(error instanceof Error ? error.message : "Quote unavailable."); setStatus("UNAVAILABLE"); } }
  return <main className="min-h-dvh bg-gt-black p-4 text-gt-fg"><section className="mx-auto max-w-md space-y-4"><p className="text-xs font-semibold uppercase tracking-[.16em] text-gt-emerald-bright">Green Tree · Telegram</p><h1 className="text-2xl font-semibold">Buy GTREE</h1><div className="glass-surface-b rounded-lg p-4"><p className="text-xs text-gt-muted">GTREE/USD</p><p className="mt-1 text-xl font-semibold">{snapshot ? `$${snapshot.gtreeUsd}` : "Unavailable"}</p><p className="mt-2 text-sm text-gt-muted">GTREE/SOL {snapshot?.priceSol ?? "—"} · SOL/USD ${snapshot?.solUsd ?? "—"}</p><p className="mt-2 text-xs text-gt-emerald-bright">{status}</p></div><label className="block text-sm"><span className="text-gt-muted">SOL input</span><input value={sol} onChange={(event) => setSol(event.target.value)} inputMode="decimal" placeholder="0.00" className="mt-2 h-12 w-full rounded-md border border-gt-border bg-gt-surface px-3 text-lg" /></label><div className="rounded-lg border border-gt-border p-4"><p className="text-xs text-gt-muted">Local estimate — not a quote</p><p className="mt-1 text-xl font-semibold">{estimate ? `${atomicToDecimal(estimate, 9)} GTREE` : "—"}</p><p className="mt-2 text-sm text-gt-muted">Foundation inventory: {inventory?.spendableGtree ?? "Unavailable"} GTREE</p></div><Button className="w-full" onClick={() => void review()} disabled={!estimate}>Review Purchase</Button><a className="block text-center text-sm text-gt-emerald-bright" href="https://gtree.land/market" target="_blank" rel="noreferrer">Open secure checkout in browser</a>{notice && <p role="status" className="text-sm text-amber-200">{notice}</p>}</section></main>;
}
